parameters:
  templating.asset.path_package.class: Checkdomain\AssetsExtraBundle\Templating\Asset\PathPackage
  templating.asset.url_package.class: Checkdomain\AssetsExtraBundle\Templating\Asset\UrlPackage
  checkdomain_assets_extra.assets_locator.class: Checkdomain\AssetsExtraBundle\Services\AssetsLocator
  assetic.filter.lessphp.class: Checkdomain\AssetsExtraBundle\Assetic\Filter\LessphpFilter
  assetic.filter.cssrewrite.class: Checkdomain\AssetsExtraBundle\Assetic\Filter\CssRewriteFilter
  
services:
  assets_locator:
    class: %checkdomain_assets_extra.assets_locator.class%
    arguments: [%checkdomain_assets_extra.assets_path%, %checkdomain_assets_extra.encrypt_bundle%]